# SPDX-License-Identifier: GPL-2.0+
#
# note this is NOT autogenerated from Makefile.am, etc
#
#
# Copyright (c) 2013, Google Inc.
#
# (C) Copyright 2000-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
# (C) Copyright 2019, SiFive Inc

obj-$(CONFIG_$(SPL_)FIT_SIGNATURE) += src/secp256k1.o
