#!/usr/bin/env python3

import csv
import sys

# secp256k1's own generator point G, compressed encoding
SECP256K1_G = "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"


if len(sys.argv) < 2:
    print(
        "This script converts BIP 374 DLEQ test vectors in a given directory to a C file that can be used in the test framework."
    )
    print("Usage: %s <dir>" % sys.argv[0])
    sys.exit(1)


def read_vectors(path):
    with open(path, newline="") as csvfile:
        return [
            row
            for row in csv.DictReader(csvfile)
            if row["point_G"] == SECP256K1_G
        ]


def byte_array(value, size, invalid_values=()):
    if value in invalid_values:
        return "{ 0x00 }"
    data = bytes.fromhex(value)
    if len(data) != size:
        raise ValueError("Expected %d bytes, got %d" % (size, len(data)))
    return "{ %s }" % ", ".join("0x%02X" % byte for byte in data)


def parse_success(value):
    value = value.upper()
    if value in {"TRUE", "1"}:
        return 1
    if value in {"FALSE", "0"}:
        return 0
    raise ValueError("Unexpected result_success value: %s" % value)


generate_vectors = read_vectors(sys.argv[1] + "/test_vectors_generate_proof.csv")
verify_vectors = read_vectors(sys.argv[1] + "/test_vectors_verify_proof.csv")

output = [
    """/**
 * Automatically generated by tools/test_vectors_dleq_generate.py.
 *
 * Test vectors according to BIP-374 (\"Discrete Log Equality Proofs\").
 */

struct dleq_generate_vector {
    unsigned char scalar_a[32];
    unsigned char point_B[33];
    unsigned char auxrand[32];
    unsigned char message[32];
    unsigned char expected_proof[64];
    int point_B_is_infinity;
    int has_message;
    int expected_success;
};

struct dleq_verify_vector {
    unsigned char point_A[33];
    unsigned char point_B[33];
    unsigned char point_C[33];
    unsigned char message[32];
    unsigned char proof[64];
    int has_message;
    int expected_success;
};

static const struct dleq_generate_vector dleq_generate_vectors[] = {"""
]

for row in generate_vectors:
    output.extend(
        [
            "    {",
            "        %s," % byte_array(row["scalar_a"], 32),
            "        %s," % byte_array(row["point_B"], 33, {"INFINITY"}),
            "        %s," % byte_array(row["auxrand_r"], 32),
            "        %s," % byte_array(row["message"], 32, {""}),
            "        %s," % byte_array(row["result_proof"], 64, {"INVALID"}),
            "        %d," % (row["point_B"] == "INFINITY"),
            "        %d," % (row["message"] != ""),
            "        %d" % (row["result_proof"] != "INVALID"),
            "    },",
        ]
    )

output.extend(
    [
        "};",
        "",
        "static const struct dleq_verify_vector dleq_verify_vectors[] = {",
    ]
)

for row in verify_vectors:
    output.extend(
        [
            "    {",
            "        %s," % byte_array(row["point_A"], 33),
            "        %s," % byte_array(row["point_B"], 33),
            "        %s," % byte_array(row["point_C"], 33),
            "        %s," % byte_array(row["message"], 32, {""}),
            "        %s," % byte_array(row["proof"], 64),
            "        %d," % (row["message"] != ""),
            "        %d" % parse_success(row["result_success"]),
            "    },",
        ]
    )

output.append("};")
print("\n".join(output))
