name: 'Run in Docker with environment'
description: 'Run a command in a Docker container, while passing explicitly set environment variables into the container.'
inputs:
  dockerfile:
    description: 'A Dockerfile that defines an image'
    required: true
  scope:
    description: 'A cached image scope'
    required: false
    default: ${{ runner.arch }}
  command:
    description: 'A command to run in a container'
    required: true
runs:
  using: "composite"
  steps:
    - uses: docker/setup-buildx-action@v3

    - uses: docker/build-push-action@v6
      id: main_builder
      continue-on-error: true
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        load: true
        cache-from: type=gha,scope=${{ inputs.scope }}

    - uses: docker/build-push-action@v6
      id: retry_builder
      if: steps.main_builder.outcome == 'failure'
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        load: true
        cache-from: type=gha,scope=${{ inputs.scope }}

    - # Workaround for https://github.com/google/sanitizers/issues/1614 .
      # The underlying issue has been fixed in clang 18.1.3.
      run: sudo sysctl -w vm.mmap_rnd_bits=28
      shell: bash

    - # Tell Docker to pass environment variables in `env` into the container.
      shell: bash
      env:
        CMD_TO_RUN: ${{ inputs.command }}
        ENV_JSON: ${{ toJSON(env) }}
      run: |
        # Use a temporary file to store the environment variables JSON
        # and pass it via an environment variable to avoid shell injection.
        echo "$ENV_JSON" > "$RUNNER_TEMP/env.json"
        docker run \
          $(jq -r 'keys[] | select(. != "CMD_TO_RUN" and . != "ENV_JSON") | "--env \(.) "' "$RUNNER_TEMP/env.json") \
          --volume "$GITHUB_WORKSPACE":"$GITHUB_WORKSPACE" \
          --workdir "$GITHUB_WORKSPACE" \
          "${{ steps.main_builder.outputs.imageid || steps.retry_builder.outputs.imageid }}" \
          bash -c '
            git config --global --add safe.directory "$1"
            eval "$2"
          ' -- "$GITHUB_WORKSPACE" "$CMD_TO_RUN"
