/* This file was automatically generated by precompute. */
#ifndef SECP256K1_PRECOMPUTED_ECMULT_H
#define SECP256K1_PRECOMPUTED_ECMULT_H
#include "group.h"
#include "ecmult.h"
#if ECMULT_TABLE_SIZE(ECMULT_WINDOW_SIZE) > 8192
   #error configuration mismatch, invalid ECMULT_WINDOW_SIZE. Try deleting precomputed_ecmult.h before the build.
#endif
#if defined(EXHAUSTIVE_TEST_ORDER)
#if EXHAUSTIVE_TEST_ORDER == 13
#define WINDOW_G 4
#elif EXHAUSTIVE_TEST_ORDER == 199
#define WINDOW_G 8
#else
   #error No known generator for the specified exhaustive test group order.
#endif
static secp256k1_ge_storage secp256k1_pre_g[ECMULT_TABLE_SIZE(WINDOW_G)];
static secp256k1_ge_storage secp256k1_pre_g_128[ECMULT_TABLE_SIZE(WINDOW_G)];
#else /* !defined(EXHAUSTIVE_TEST_ORDER) */
#define WINDOW_G ECMULT_WINDOW_SIZE
extern const secp256k1_ge_storage secp256k1_pre_g[ECMULT_TABLE_SIZE(WINDOW_G)];
extern const secp256k1_ge_storage secp256k1_pre_g_128[ECMULT_TABLE_SIZE(WINDOW_G)];
#endif /* EXHAUSTIVE_TEST_ORDER */
#undef S
#endif /* SECP256K1_PRECOMPUTED_ECMULT_H */
